IINemo/lm-polygraph

- examples/configs/polygraph_eval_babiqa.yaml
- examples/configs/polygraph_eval_coqa.yaml
- examples/configs/polygraph_eval_wmt14_ende.yaml
- examples/configs/polygraph_eval_wmt14_enfr.yaml
- src/lm_polygraph/stat_calculators/sample.py
- src/lm_polygraph/utils/model.py
- Немного обновил конфиги так, чтобы везде был правильно указан `save_path`
- Исправил семплирование для blackbox методов
1. в семплированных ответах `blackbox_sample_texts` и в `blackbox_greedy_texts` сохранялся промпт, из-за чего методы использовали промпт+ответ для подсчета скоров
2.  для `blackbox_sample_texts` неправильно группировались ответы
3.  параметр `top_k` для `blackbox_sample_texts` у нас использовался по умолчанию равный 1, из-за чего получали всегда одинаковые ответы
Стоит заметить, что большая часть экспериментов отработала корректно, т.к. в бенчмарке, если у нас есть `sample_texts` (а он считается корректно), то он копируется в `blackbox_sample_texts` и отдельно для blackbox не запускается. А `sample_texts` у нас считается во многих методах, поэтому ошибка была только …
> Fix blackbox sampling

- src/lm_polygraph/utils/manager.py
Сейчас если эстиматор в какой-то момент вылетел с ошибкой мы убираем его из `self.estimators` но то что он успел наоценивать остается в self.estimations и в конце эксперимента падает с ошибкой мисматча длины листа с ue и листа с метрикой (типа rouge).
Теперь если эстиматор вылетел с ошибкой удаляются в том числе и результаты его работы.
Можно эту проблему решить тоньше но пока вот так.
> Prevent shape mismatch

- examples/configs/polygraph_eval_ood.yaml
- examples/corrupt_dataset.py
- scripts/polygraph_eval
- scripts/polygraph_eval_ood
- src/lm_polygraph/estimators/mahalanobis_distance.py
- src/lm_polygraph/estimators/ppl_md.py
- src/lm_polygraph/estimators/rde.py
- src/lm_polygraph/estimators/relative_mahalanobis_distance.py
- src/lm_polygraph/ue_metrics/__init__.py
- src/lm_polygraph/ue_metrics/roc_auc.py
- src/lm_polygraph/utils/dataset.py
- src/lm_polygraph/utils/manager.py
- src/lm_polygraph/utils/ood_detection.py
Example of usage:
Corrupt dataset:
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG=../examples/configs/polygraph_eval_aeslc.yaml python ./examples/corrupt_dataset.py prompt='' model="facebook/opt-350m" 
ID dataset:
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG=../examples/configs/polygraph_eval_aeslc.yaml python ./scripts/polygraph_eval device="cuda:0" batch_size=1 subsample_train_dataset=100 subsample_background_train_dataset=100 model="facebook/opt-350m" subsample_eval_dataset=100
OOD dataset:
CUDA_VISIBLE_DEVICES=0 HYDRA_CONFIG=../examples/configs/polygraph_eval_aeslc.yaml python ./scripts/polygraph_eval device="cuda:0" batch_size=1 model="facebook/opt-350m" dataset=./workdir/output/ats/facebook/opt-350m/aeslc/2023-11-22/15-47-17/aeslc_corrupted.csv text_column=email_body_corrupted label_column=subject_line …
> Ood detection optimized

- src/lm_polygraph/utils/dataset.py
np.array(list).tolist() is very memory-inefficient and causes OOMs when subsampling huge datasets (i.e. trainset of wmt14).
> Do not copy dataset when subsampling

- src/lm_polygraph/stat_calculators/extract_claims.py
This PR fixes a bug introduced in the previous claim-level PR (https://github.com/IINemo/lm-polygraph/pull/192) where obtaining the current `match_word` would fail if all match words were already aligned.
> Fix claims extraction

- .github/workflows/python-publish.yml
- pyproject.toml
- requirements.txt
- src/lm_polygraph/generation_metrics/alignscore_utils.py
In this commit I created new Github Action that does the following:
1. Detects when new release is created
2. Reads release version and assigns it to package version
3. Publishes package to PyPI
It also needs pypi token to be set in secrets
It also requires all release versions to be in format "v{some correct new version of pypi}", e.g. v0.1.2.dev3
I also removed en-core-web-sm package dependency, since I couldn't release package because of it
Now it will be installed at runtime in code
> Automatic publish to PyPI when creating new release

- src/lm_polygraph/ue_metrics/pred_rej_area.py
Added parameter `max_rejection` to PRR metric to use 50% (or any percentage) of the curve
> added parameter to PRR to compute 50% of the curve

- src/lm_polygraph/estimators/__init__.py
- src/lm_polygraph/estimators/claim/random_baseline.py
The random baseline is useful for reporting claim level scores such as F1 or PR-AUC.
> Random baseline for claim uncertainty

- requirements.txt
Spacy 3.8.0 and up depends on numpy>2.0, while COMET only works with numpy<2.0, which causes long backtracking during installation.
Pinning spacy<3.8.0 to speed up installation.
> Set upper limit on spacy version

- examples/claim_level_example.ipynb
- examples/claim_level_example_ar.ipynb
- examples/claim_level_example_ru.ipynb
- examples/claim_level_example_zh.ipynb
- `aligned_tokens` was renamed to `align_token_ids` earlier, fixing it in notebooks
- renamed notebooks for consistency
> Update claim-level examples

- src/lm_polygraph/model_adapters/whitebox_model_basic.py
- src/lm_polygraph/utils/model.py
- Previously, the WhiteboxModel was adding two starting symbols \<s\> in the beginning of the generation \<s\>\<s\> in case of using apply_chat_template (one from apply_chat_template, one from tokenize).
- Fixed the implementation of WhiteboxModelBasic by adding tokenizer arguments and missing device() implementation
> Fix tokenization special symbols2

- src/lm_polygraph/stat_calculators/extract_claims.py
Fixed a bug where `claim_texts_concatenated` would only contain the first text in the batch.
> Fix multi-batch stats in extract_claims.py

- src/lm_polygraph/utils/manager.py
Add logging of nans in evaluation metrics and uncertainty metrics.
Instead of removing instances for which ue score returned nan, we clip ue scores, so they still participate in evaluation. That prevents reporting of the misleadingly high results for ue methods that report a lot of nans.
> Fix evaluation nans

- src/lm_polygraph/utils/model.py
resolves #322
This PR refactors `model.py` to make `BlackboxModel` handle parameters consistently with `WhiteboxModel`:
- Rename `parameters` to `generation_parameters` in `BlackboxModel` for consistency
- Create a shared `_validate_args` function that works for both model types
- Update `BlackboxModel.generate_texts()` and `generate()` to properly use default parameters
- Update the static factory methods to correctly extract and pass generation parameters
factory methods to correctly extract and pass generation parameters
> Make BlackboxModel use GenerationParameters consistently with WhiteboxModel

- src/lm_polygraph/estimators/max_probability.py
Refactor the `MaximumTokenProbability` estimator to compute logarithmic values instead of raw probabilities.
This estimator operates at token-level and is not used directly in any of the currently supported benchmarks, which evaluate at the sequence- or claim-level, so this change does not affect benchmark results.
> Calculate logarithms in MaximumTokenProbability

- examples/configs/polygraph_eval_mmlu.yaml
- examples/configs/polygraph_eval_person_bio_ar.yaml
- examples/configs/polygraph_eval_person_bio_en_jais.yaml
- examples/configs/polygraph_eval_person_bio_en_mistral.yaml
- examples/configs/polygraph_eval_person_bio_ru.yaml
- examples/configs/polygraph_eval_person_bio_zh.yaml
- scripts/polygraph_eval
- src/lm_polygraph/utils/model.py
1. Standardize the configs with the parameter `instruct` (in some configs, this parameter was missing).
2. Added application of the chat template only for instruct models.
> Fix for the chat template

- requirements.txt
- src/lm_polygraph/defaults/register_default_stat_calculators.py
- src/lm_polygraph/defaults/stat_calculator_builders/utils.py
- src/lm_polygraph/stat_calculators/greedy_alternatives_nli.py
- src/lm_polygraph/stat_calculators/semantic_matrix.py
- src/lm_polygraph/utils/deberta.py
Improve NLI performance and memory footprint by:
- torch.no_grad where deberta is invoked
- offload from gpu only after all processing is finished
- do memory sweeps on each iteration
>  Deberta memory fix

- src/lm_polygraph/utils/estimate_uncertainty.py
- src/lm_polygraph/utils/generation_parameters.py
Previously, it was impossible to configure max_new_tokens parameter in estimate_uncertainty function.
> Fix max new tokens in estimate_uncertainty function

- requirements.txt
- scripts/polygraph_eval
- src/lm_polygraph/utils/generation_parameters.py
- src/lm_polygraph/utils/model.py
Adds GenerationParametersFactory that ingests user-specified generation params and native model params, and outputs GenerationParameters object with the following priority rule: user config > model config > hard-coded defaults.
Only works for non-vLLM whitebox models, otherwise behavior is unchanged.
> Gen config fix

- dataset_builders/build_dataset.py
- dataset_builders/builders/coqa.py
- dataset_builders/builders/gsm8k.py
- dataset_builders/builders/mmlu.py
- dataset_builders/builders/samsum.py
- dataset_builders/builders/trivia_qa.py
- dataset_builders/builders/truthfulqa.py
- dataset_builders/builders/wmt.py
- dataset_builders/builders/xsum.py
- dataset_builders/manager.py
- examples/configs/estimators/default_estimators.yaml
- examples/configs/instruct/model/default_causal.py
- examples/configs/model/default_causal.py
- examples/configs/model/gemma_3.py
- examples/configs/polygraph_eval_coqa_simple_instruct.yaml
- examples/configs/polygraph_eval_gsm8k_simple_instruct.yaml
- examples/configs/polygraph_eval_mmlu_simple_instruct.yaml
- examples/configs/polygraph_eval_samsum_simple_instruct.yaml
- examples/configs/polygraph_eval_triviaqa_simple_instruct.yaml
- examples/configs/polygraph_eval_truthfulqa_simple_instruct.yaml
- examples/configs/polygraph_eval_wmt14_deen_simple_instruct.yaml
- examples/configs/polygraph_eval_wmt14_fren_simple_instruct.yaml
- examples/configs/polygraph_eval_wmt19_deen_simple_instruct.yaml
- examples/configs/polygraph_eval_wmt19_ruen_simple_instruct.yaml
- examples/configs/polygraph_eval_xsum_simple_instruct.yaml
Added simplified prompts for instruction-tuned models. The main motivation for using simplified prompts is that overly strict instructions tend to make models overconfident, which negatively impacts uncertainty quantification performance.
Rationale behind each prompt:
1. CoQA, TriviaQA - a simple instruction "Answer the following question as briefly as possible" performs well. Modern LLMs produce answers in the consistent format. This prompt also better reflects real-world question formats.
2. MMLU, GSM8k - use more detailed instructions with a strict, but not overly strict format. Similar to the prompt structure used in Llama 3.1 Instruct evals: https://huggingface.co/datasets/meta-llama/Llama-3.1-8B-Instruct-evals 
3. TruthfulQA - I tested dozens of prompts using the few-shot examples …
> Added simple prompts for instruct models

- src/lm_polygraph/utils/manager.py
Helps to calculate PRR and other ue metrics for managers that were manually modified:
```python
from lm_polygraph.utils.manager import UEManager
from lm_polygraph.ue_metrics import *
man = UEManager.load("path/to/man")
man.estimations[('sequence', 'new_method_name')] = values
man.ue_metrics = [PredictionRejectionArea(max_rejection=0.5),]
man.eval_ue()
man.save("path/to/man")
```
> Make evaluation of ue separate step within separate function

- src/lm_polygraph/estimators/kernel_language_entropy.py
Adds fallback to numpy <1.25 return values of `np.linalg.eig` if error is thrown
> Fallback to numpy 1 when error is thrown
