src/lm_polygraph/estimators/lexical_similarity.py
src/lm_polygraph/estimators/monte_carlo_normalized_sequence_entropy.py

Fixed method Lexical Similarity for BLEU score
Fixed method Monte Carlo Normalized Sequence Entropy (fixed length-normalization)

fixed methods LexSim & MC NSE

---

src/lm_polygraph/estimators/lexical_similarity.py

Update for BLEU in LexSim, for consistency with Rouge metrics

updated bleu for lexsim

---

scripts/polygraph_server
src/lm_polygraph/app/client/assets/js/index.js
src/lm_polygraph/app/client/assets/js/select.js
src/lm_polygraph/app/client/index.html
src/lm_polygraph/app/service.py
src/lm_polygraph/app/service_helpers.py

Allow to do `polygraph_server --all-methods` and `python -m lm_polygraph.app.service --all-methods` to show all known methods and models

Smart select

---

src/lm_polygraph/estimators/mahalanobis_distance.py
src/lm_polygraph/estimators/rde.py
src/lm_polygraph/estimators/relative_mahalanobis_distance.py

All is okey. Just added some comments for clarification within review

added review with comments

---

README.md
scripts/polygraph_eval
scripts/polygraph_eval_configs/custom_estimator_example.py
scripts/polygraph_eval_configs/custom_estimator_example.yaml
scripts/polygraph_eval_configs/default.yaml
scripts/requirements.txt

How to use:
```./polygraph_eval --use_hydra```
How to use with custom config:
```./polygraph_eval --use_hydra -cn custom_estimator_example```

Add hydra to polygraph_eval

---

scripts/polygraph_eval
src/lm_polygraph/utils/dataset.py
src/lm_polygraph/utils/model.py

blackbox fixes

---

scripts/polygraph_eval
scripts/requirements.txt
test/configs/test_config.yaml
test/configs/test_polygraph_eval.yaml
test/test_lm_polygraph.py

Launch with `pytest`. Testing takes about a minute.

Add tests for polygraph_eval

---

requirements.txt
src/lm_polygraph/generation_metrics/bert_score.py
src/lm_polygraph/generation_metrics/sbert.py

I've decided to add sentence-transofrmers as it seems stable and reliable.
It's quite small though
all-mpnet-base-v2 is their best model and it seems way to go with 8.5 milions of download
There is leaderboard for sequence embedding, but there is no deberta there
https://huggingface.co/spaces/mteb/leaderboard

Sbert and bert-score metrics

---

src/lm_polygraph/__init__.py
src/lm_polygraph/utils/__init__.py
src/lm_polygraph/utils/manager.py

Example:
```
from lm_polygraph.utils import estimate_uncertainty, WhiteboxModel
from lm_polygraph.estimators import *
model = WhiteboxModel.from_pretrained(
"bigscience/bloomz-3b",
device="cuda:0",
)
ue_method = MeanPointwiseMutualInformation()
input_text = "Who is George Bush?"
estimate_uncertainty(model, ue_method, input_text=input_text)
```

Better imports

---

src/lm_polygraph/utils/manager.py
test/test_lm_polygraph.py

Выносит расчет ансамблевых метрик после расчета метрик одной модели, чтобы избежать загрузки на карту сразу модели и ансамбля.

Calculate ensembles after single-model stuff

---

src/lm_polygraph/stat_calculators/greedy_probs.py

Log softmax bug fixed

---

src/lm_polygraph/app/service.py
src/lm_polygraph/estimators/relative_mahalanobis_distance.py
src/lm_polygraph/utils/dataset.py
src/lm_polygraph/utils/manager.py
src/lm_polygraph/utils/processor.py
src/lm_polygraph/utils/token_restoration.py

Goal of this PR is to keep information about exception even when they are ignored, and present info about failures in a convenient way after the calculation is done.

Error Handling

---

src/lm_polygraph/stat_calculators/embeddings.py
src/lm_polygraph/stat_calculators/greedy_probs.py
src/lm_polygraph/stat_calculators/sample.py

Added min_new_tokens instead of min_length, since min_length overrided with input_length+min_new_tokens in all cases

added min_new_tokens

---

examples/configs/polygraph_eval_mmlu.yaml
examples/configs/polygraph_eval_wmt19_deen.yaml
src/lm_polygraph/utils/dataset.py

- Only impose subject limit on mmlu if `len(subject) > limit`
- Use different splits
- Change XSum to continuation prompt
- Add wmt19

Change mmlu config

---

examples/configs/polygraph_eval_gsm8k.yaml

increase max_new_tokens
added normilze: true for accuracy

updated configs for gsm8k

---

src/lm_polygraph/stat_calculators/entropy.py

Fix entropy calculation

---

README.md
scripts/polygraph_eval
src/lm_polygraph/generation_metrics/__init__.py
src/lm_polygraph/generation_metrics/bleu.py

1. Added BLEU
2. Updated code example in README
3. Use OpenAIFactCheck in eval script only for claim-level

Added BLEU

---

src/lm_polygraph/utils/dataset.py

Fixes few-shot prompting for MMLU when few shot examples are taken from different subjects.

Use same subject for few shot as for the question itself

---

examples/configs/polygraph_eval_xsum.yaml
scripts/polygraph_eval
src/lm_polygraph/utils/dataset.py

Ensures results from base model benchmarks are reproducible from current main branch.

Ensure reproducibility of old results

---

README.md

More comprehensive and up-to-date installation instruction, plus usage example with new model loading approach.

Align README with docs

---

examples/claim_level_example.ipynb
examples/zh_claim_level_example.ipynb
requirements.txt
src/lm_polygraph/generation_metrics/openai_fact_check.py
src/lm_polygraph/stat_calculators/extract_claims.py
src/lm_polygraph/utils/openai_chat.py

- Add multithreading for openai
- Upgrade openai api
- OPENAI_KEY => OPENAI_API_KEY
- Add parametrization for openai prompts in the claim extractor and fact checker

Multithreading for openai, upgrade openai api

---

.github/workflows/python-app.yml
CONTRIBUTING.md
src/lm_polygraph/estimators/num_sem_sets.py
test/local/test_benchmark.py
test/test_estimators.py

Adds test cases for benchmark (smoke tests checking exit code 0) and for whitebox estimators through `estimate_uncertainty`.

Add benchmark and estimators tests

---

docs/conf.py

https://readthedocs.org/projects/lm-polygraph/builds/26181135/ (current main)
https://readthedocs.org/projects/lm-polygraph/builds/26204346/ (this branch)

Use xelatex engine

---

examples/configs/default_calculators.yaml
examples/configs/polygraph_eval_aeslc.yaml
examples/configs/polygraph_eval_babiqa.yaml
examples/configs/polygraph_eval_coqa.yaml
examples/configs/polygraph_eval_gsm8k.yaml
examples/configs/polygraph_eval_mmlu.yaml
examples/configs/polygraph_eval_triviaqa.yaml
examples/configs/polygraph_eval_wmt14_deen.yaml
examples/configs/polygraph_eval_wmt14_fren.yaml
examples/configs/polygraph_eval_wmt19_deen.yaml
examples/configs/polygraph_eval_xsum.yaml
src/lm_polygraph/defaults/stat_calculator_builders/default_TrainingStatisticExtractionCalculator.py
src/lm_polygraph/estimators/ppl_md.py
src/lm_polygraph/stat_calculators/greedy_probs.py
src/lm_polygraph/stat_calculators/statistic_extraction.py
src/lm_polygraph/utils/manager.py

1. Fixed reproducibility with a new estimators and calculators for density-based methods
2. Speed up calculation of UQ metrics (removed duplicate loops for a random UQ curve)
3. Fixed issues with GPU OOM for the PPLMD methods

Fixed issues with reproducibility

---

src/lm_polygraph/estimators/deg_mat.py
src/lm_polygraph/estimators/eccentricity.py
src/lm_polygraph/estimators/eig_val_laplacian.py
src/lm_polygraph/estimators/num_sem_sets.py
src/lm_polygraph/estimators/semantic_entropy_token.py
src/lm_polygraph/generation_metrics/bart_score.py
src/lm_polygraph/generation_metrics/bert_score.py
src/lm_polygraph/generation_metrics/sbert.py
src/lm_polygraph/stat_calculators/bart_score.py
src/lm_polygraph/stat_calculators/model_score.py
src/lm_polygraph/utils/builder_stat_calculator_simple.py
src/lm_polygraph/utils/model.py
src/lm_polygraph/utils/processor.py
src/lm_polygraph/utils/token_restoration.py

Replaced print functions with logging functions.

Replace print with a log function

---

examples/configs/default_claim_estimators.yaml
examples/configs/default_estimators.yaml
src/lm_polygraph/estimators/__init__.py
src/lm_polygraph/estimators/focus.py
src/lm_polygraph/utils/factory_estimator.py
test/test_estimators.py

Remove focus from standard estimators due to various issues.

Hide focus

---

scripts/polygraph_eval
src/lm_polygraph/defaults/register_default_stat_calculators.py
src/lm_polygraph/defaults/stat_calculator_builders/default_ClaimsExtractor.py
src/lm_polygraph/defaults/stat_calculator_builders/utils.py
src/lm_polygraph/generation_metrics/openai_fact_check.py
src/lm_polygraph/stat_calculators/extract_claims.py
src/lm_polygraph/utils/deberta.py
src/lm_polygraph/utils/manager.py

Merge changes to claim-level evaluation from dev

Fix claim level

---

.dockerignore
Dockerfile
README.md

Fix Dockerfile

---

scripts/polygraph_eval
src/lm_polygraph/defaults/register_default_stat_calculators.py
src/lm_polygraph/model_adapters/whitebox_model_basic.py

Add option for logging into wandb

Add wandb support + minor fixes

---

src/lm_polygraph/defaults/stat_calculator_builders/default_ClaimsExtractor.py
src/lm_polygraph/estimators/__init__.py
src/lm_polygraph/estimators/focus.py
src/lm_polygraph/generation_metrics/openai_fact_check.py
src/lm_polygraph/utils/openai_chat.py

1. Fixes to focus
2. Added parameters for openai_chat
3. Added parameters for openai_fact_check
4. Added attention score to __init__

Multiple small fixes

---

src/lm_polygraph/defaults/register_default_stat_calculators.py
src/lm_polygraph/model_adapters/whitebox_model_vllm.py

- Fixed the parameter handling for vLLM
- Fixed default cache directory for ClaimsExtractor

Minor fixes 2

---

scripts/polygraph_eval
src/lm_polygraph/defaults/register_default_stat_calculators.py

Added deberta_batch_size parameter

Added deberta_batch_size parameter

---

examples/configs/model/vllm.yaml
test/configs/model/vllm.yaml
test/configs/test_polygraph_eval_vllm.yaml
test/local/test_vllm.py

1. Reduced `gpu_memory_utilization` in the vLLM configs
2. Fixed an issue during vLLM testing

Fixed vLLM test and configs
